version: "3.7"

services:
  vapi:
    image: ecency/api:latest
    environment:
      - PRIVATE_API_ADDR
      - PRIVATE_API_AUTH
      - HIVESIGNER_SECRET
      - SEARCH_API_ADDR
      - SEARCH_API_SECRET
      - CHAINSTACK_API_KEY
      - CHAINZ_API_KEY
      - BLOCKSTREAM_CLIENT_ID
      - BLOCKSTREAM_CLIENT_SECRET
    restart: always
    ports:
      - "4000:4000"
    hostname: vapi
    networks:
      - vision

  web:
    image: ecency/vision-next:develop
    stop_grace_period: 30s
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        delay: 15s
        order: start-first
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        order: start-first
    environment:
      - USE_PRIVATE
      - INTERNAL_API_HOST=http://vapi:4000
      - HIVESIGNER_SECRET
      - PLAUSIBLE_API_KEY
      - NEXT_PUBLIC_GMAPS_MAP_ID
      - NEXT_PUBLIC_GMAPS_API_KEY
      - MATTERMOST_BASE_URL
      - MATTERMOST_ADMIN_TOKEN
      - MATTERMOST_TEAM_ID
      - MATTERMOST_WS_ALLOWED_ORIGINS
      - THREESPEAK_EMBED_API_KEY
    restart: always
    ports:
      - "3000:3000"
    hostname: web
    networks:
      - vision

networks:
  vision:
    external: true
