version: "3.7"

services:
  vapi:
    image: ecency/api:latest
    environment:
      - PRIVATE_API_ADDR
      - PRIVATE_API_AUTH
      - HIVESIGNER_SECRET
      - SEARCH_API_ADDR
      - SEARCH_API_SECRET
    restart: always
    ports:
      - "4000:4000"
    hostname: vapi
    networks:
      - vision

  web:
    image: ecency/vision-next:latest
    deploy:
      replicas: 4
    environment:
      - NEXT_PUBLIC_USE_PRIVATE
      - NEXT_PUBLIC_HS_CLIENT_SECRET
      - NODE_ENV
      - PLAUSIBLE_API_KEY
      - GMAPS_MAP_ID
      - GMAPS_API_KEY
    restart: always
    ports:
      - "3000:3000"
    hostname: web
    networks:
      - vision

networks:
  vision:
    external: true
