// next-env.d.ts carries Next's ambient declarations for static asset imports
// (*.svg, *.png, ...), but it is generated by `next build`/`next dev` and is
// gitignored, so a clean checkout has none of them and `tsc --noEmit` fails on
// every asset import. Referencing the same types here keeps the typecheck
// self-contained instead of depending on a prior build.
/// <reference types="next/image-types/global" />
