name: Any build for packages
on:
  push:
    branches:
      - '*'
jobs:
  build:
    if: github.ref_name != 'main'
    runs-on: ubuntu-latest
    env:
      VITE_HELIUS_API_KEY: ${{ secrets.VITE_HELIUS_API_KEY }}
      VITE_BITQUERY_API_KEY: ${{ secrets.VITE_BITQUERY_API_KEY }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, lint and/or test
        run: |
          yarn
      - name: build
        run: yarn build
        env:
          CI: true
