name: Any build for packages
on:
  push:
    branches:
      - '*'
jobs:
  build:
    if: github.ref_name != 'main'
    runs-on: ubuntu-latest
    env:
      VITE_HELIUS_API_KEY: ${{ secrets.VITE_HELIUS_API_KEY }}
      VITE_BITQUERY_API_KEY: ${{ secrets.VITE_BITQUERY_API_KEY }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - uses: pnpm/action-setup@v3
        with:
          version: 10.15.1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
        env:
          CI: true
