name: PR build
on:
  push:
    branches:
      - 'bugfix/*'
      - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint and/or test
      run: |
        yarn
    - name: build
      run: yarn build
      env:
        CI: true
